INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('url', 'http://bereso/');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('dbversion', '3.6');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('ocr_enabled', '0');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('ocr_password', 'PASSWORD_FOR_OCR_AGENT');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('login_motd', '');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('session_lifetime', '2592000');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('datetimestring', 'd.m.Y H:i:s');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('timezone', 'Europe/Berlin');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('new_amount_images', '5');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('images_thumbnail_height', '200');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('https_redirect', '0');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('images', 'images/');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('user_log', '0');
INSERT INTO `bereso_config` (`config_name`, `config_value`) VALUES ('agent_ocr_log', '0');
