-- Create a new Template for Bereso
-- replace NEW_TEMPLATE_ID with the next free ID
INSERT INTO `bereso_template` (`template_id`, `template_name`) VALUES ('NEW_TEMPLATE_ID','Rezeptverwaltung');

INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_tags_categorie','Kategorien');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_categories','Kategorien');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_random_item','Zufalls Rezept');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_logout','abmelden');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_tags_all_items','Alle Rezepte');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_tags_all_shared_items','Alle geteilten Rezepte');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_search_results','Suchergebnisse f&uuml;r');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_search_error','Suchanfrage enth&auml;lt nicht erlaubte Zeichen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','list_tags_items_with','Rezepte mit');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','show_created','Erstellt am');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','show_changed','Ge&auml;ndert am');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_show_edit_item','Rezept editieren');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_show_delete_item','Rezept l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_show_stop_sharing','Freigabe beenden');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_show_start_sharing','Rezept freigeben');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','show_sharing_external_link','Externer Freigabelink');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','main_navigation_share_import_item','Rezept importieren');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','delete_confirm','L&Ouml;SCHEN best&auml;tigen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','delete_item','Rezept l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_item','Neues Rezept');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_preview_image','Vorschaubild');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_save','Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_item_page','Rezeptseite');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_description','Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_name','Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_saved','Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_error_name_characters','Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_error_text_characters','Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_error_filetype','Eintrag <b>NICHT</b> gespeichert. Falscher Dateityp! Nur JPG und PNG Dateien verwenden.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_error_filesize','Eintrag <b>NICHT</b> gespeichert. Maximale Datei Uploadgr&ouml;sse &uuml;berschritten.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_entry_error_missing','Eintrag <b>NICHT</b> gespeichert. Name fehlt oder Vorschaubild/Seitenbild(er) Upload fehlerhaft!');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_saved','Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_error_name_characters','Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_error_text_characters','Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_error_name_missing','Eintrag <b>NICHT</b> gespeichert. Name fehlt!');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_error_filetype','Bild <b>NICHT</b> gespeichert. Falscher Dateityp! Nur JPG und PNG Dateien verwenden!');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_entry_error_filesize','Eintrag <b>NICHT</b> gespeichert. Maximale Datei Uploadgr&ouml;sse &uuml;berschritten.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_image_saved','Bild gespeichert.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_save','Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_name','Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_description','Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_delete_confirm','L&Ouml;SCHEN best&auml;tigen!');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_delete_image','Bild l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_image_delete','L&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_item','Rezept bearbeiten');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_item_page','Rezeptseite');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_preview_image','Vorschaubild');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','new_add_hashtag','= Hashtag einf&uuml;gen =');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID','edit_add_hashtag','= Hashtag einf&uuml;gen =');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'list_tags_all_favorite_items', 'Lieblingsrezepte');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'main_navigation_show_stop_favorite', 'Favorit entfernen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'main_navigation_show_start_favorite', 'Favorit hinzuf&uuml;gen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'list_tags_taggroup_with', 'Tag Gruppe:');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'main_navigation_new_taggroup', 'Neue Tag Gruppe');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup', 'Neue Tag Gruppe');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_name', 'Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_description', 'Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_add_hashtag', '= Hashtag einf&uuml;gen =');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_save', 'Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_entry_saved', 'Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_entry_error_name_characters', 'Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_entry_error_text_characters', 'Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'new_taggroup_entry_error_name_exists', 'Eintrag <b>NICHT</b> gespeichert. Name der Tag Gruppe existiert bereits.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'delete_taggroup', 'Tag Gruppe l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'delete_taggroup_confirm', 'L&Ouml;SCHEN best&auml;tigen!');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'main_navigation_list_tags_edit_taggroup', 'Tag Gruppe editieren');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'main_navigation_list_tags_delete_taggroup', 'Tag Gruppe l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup', 'Tag Gruppe bearbeiten');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_name', 'Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_description', 'Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_add_hashtag', '= Hashtag einf&uuml;gen =');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_save', 'Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_entry_saved', 'Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_entry_error_name_characters', 'Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_entry_error_text_characters', 'Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`,`template_text_name`,`template_text_text`) VALUES ('NEW_TEMPLATE_ID', 'edit_taggroup_entry_error_name_exists', 'Eintrag <b>NICHT</b> gespeichert. Name der Tag Gruppe existiert bereits.');
