-- Add Template 3 - DE Projektverwaltung
INSERT INTO `bereso_template` (`template_id`, `template_name`) VALUES (3, 'Projektverwaltung');

INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_tags_categorie', 'Kategorien');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_categories', 'Kategorien');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_random_item', 'Zufalls Projekt');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_new_recipe', 'Neues Projekt');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_logout', 'abmelden');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_tags_all_items', 'Alle Projekte');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_tags_all_shared_items', 'Alle geteilten Projekte');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_search_results', 'Suchergebnisse f&uuml;r');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_search_error', 'Suchanfrage enth&auml;lt nicht erlaubte Zeichen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'list_tags_items_with', 'Projekte mit');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'show_created', 'Erstellt am');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'show_changed', 'Ge&auml;ndert am');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_show_edit_item', 'Projekt editieren');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_show_delete_item', 'Projekt l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_show_stop_sharing', 'Freigabe beenden');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_show_start_sharing', 'Projekt freigeben');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'show_sharing_external_link', 'Externer Freigabelink');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'main_navigation_share_import_item', 'Projekt importieren');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'delete_confirm', 'L&Ouml;SCHEN best&auml;tigen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'delete_item', 'Projekt l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_item', 'Neues Projekt');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_preview_image', 'Vorschaubild');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_save', 'Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_item_page', 'Bild');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_description', 'Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_name', 'Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_saved', 'Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_error_name_characters', 'Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_error_text_characters', 'Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_error_filetype', 'Eintrag <b>NICHT</b> gespeichert. Falscher Dateityp! Nur JPG und PNG Dateien verwenden.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_error_filesize', 'Eintrag <b>NICHT</b> gespeichert. Maximale Datei Uploadgr&ouml;sse &uuml;berschritten.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_entry_error_missing', 'Eintrag <b>NICHT</b> gespeichert. Name fehlt oder Vorschaubild/Seitenbild(er) Upload fehlerhaft!');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_saved', 'Eintrag gespeichert');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_error_name_characters', 'Eintrag <b>NICHT</b> gespeichert. Name enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_error_text_characters', 'Eintrag <b>NICHT</b> gespeichert. Text enth&auml;lt nicht erlaubte Zeichen.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_error_name_missing', 'Eintrag <b>NICHT</b> gespeichert. Name fehlt!');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_error_filetype', 'Bild <b>NICHT</b> gespeichert. Falscher Dateityp! Nur JPG und PNG Dateien verwenden!');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_entry_error_filesize', 'Eintrag <b>NICHT</b> gespeichert. Maximale Datei Uploadgr&ouml;sse &uuml;berschritten.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_image_saved', 'Bild gespeichert.');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_save', 'Speichern');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_name', 'Name');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_description', 'Beschreibung');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_delete_confirm', 'L&Ouml;SCHEN best&auml;tigen!');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_delete_image', 'Bild l&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_image_delete', 'L&ouml;schen');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_item', 'Projekt bearbeiten');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_item_page', 'Bild');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_preview_image', 'Vorschaubild');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'new_add_hashtag', '= Hashtag einf&uuml;gen =');
INSERT INTO `bereso_template_text` (`template_text_template_id`, `template_text_name`, `template_text_text`) VALUES (3, 'edit_add_hashtag', '= Hashtag einf&uuml;gen =');